CREATE OR REPLACE TYPE ty_user AS OBJECT
(
  ID            NUMBER
  ,WORKER_ID     NUMBER
  ,USERNAME      VARCHAR2(120 CHAR)
  ,PASSWORD      VARCHAR2(120 CHAR) 


  ,CONSTRUCTOR FUNCTION ty_user RETURN SELF AS RESULT
)
/
CREATE OR REPLACE TYPE BODY ty_user IS

  CONSTRUCTOR FUNCTION ty_user RETURN SELF AS RESULT IS
  BEGIN
         SELF.ID := ID;
         SELF.WORKER_ID := WORKER_ID;
         SELF.USERNAME := USERNAME;  
         SELF.PASSWORD := PASSWORD;
    RETURN;
  END;
END;
/
