CREATE OR REPLACE TYPE ty_worker AS OBJECT
(
  ID            NUMBER
  ,WORKER_ID     NUMBER
  ,USERNAME      VARCHAR2(120 CHAR)
  ,PASSWORD      VARCHAR2(120 CHAR) 


  ,CONSTRUCTOR FUNCTION ty_worker RETURN SELF AS RESULT
)
/
CREATE OR REPLACE TYPE BODY ty_worker IS

  CONSTRUCTOR FUNCTION ty_worker RETURN SELF AS RESULT IS
  BEGIN
         SELF.ID := ID;
    RETURN;
  END;
END;
/
